### ISSUE TITLE
SCORE update in the latest build

### ISSUE THREAD

**Issue by dlancer** [jessemillar/pta#30]
Latest build is tested on real hardware? SCORE is updated properly?
I use your game for simavr-arduboy testing at the moment and it seems what game speed now looks good.
But now SCORE is not updated (always zero) in the  simulation: https://github.com/jessemillar/crates/blob/2693f31a130c0ff4dfe3e17dba7f6bc015d54a2d/player.h#L24
**abs(speed)** is always less then **turnRate** in the simulation.

**Comment by jessemillar** [comment]
@dlancer Very good catch. I meant to type `turnSpeed` instead of `turnRate` on that line. Fixed. Thanks!
